-- SELECT * FROM customer;
-- SELECT CONCAT(first_name,' ',last_name) AS full_name FROM customer;
-- SELECT DISTINCT create_date FROM customer;
-- SELECT * FROM customer ORDER BY first_name DESC;
-- SELECT * FROM film;
-- SELECT film_id, title,description, release_year, rental_rate FROM film ORDER BY rental_rate ASC;
-- SELECT * FROM address;
-- SELECT address, phone FROM address WHERE district = 'Texas';
-- SELECT * FROM film WHERE film_id IN (15,150);
-- SELECT film_id, title,description,length,rental_rate FROM film WHERE title = 'The curious case of Benjamin Button';
-- SELECT film_id, title,description,length,rental_rate FROM film WHERE title LIKE 'Th%'
-- SELECT * FROM film ORDER BY rental_rate ASC LIMIT 10;
-- SELECT * FROM film ORDER BY rental_rate OFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY;
-- SELECT * FROM customer;
-- SELECT * FROM payment;
-- SELECT customer.first_name, customer.last_name, payment.amount, payment.payment_date FROM customer JOIN payment ON customer.customer_id = payment.customer_id ORDER BY customer.customer_id;
-- SELECT * FROM inventory;
-- SELECT film.film_id, film.title FROM film LEFT JOIN inventory ON film.film_id = inventory.film_id WHERE inventory.film_id IS NULL;
-- SELECT * FROM city;
-- SELECT * FROM country;
-- SELECT city.city_id, city.city, country.country FROM city JOIN country ON city.country_id = country.country_id;
-- SELECT * FROM payment;
-- SELECT customer.customer_id, customer.first_name, customer.last_name, payment.amount, payment.payment_date, payment.staff_id FROM customer JOIN payment ON customer.customer_id=payment.customer_id ORDER BY payment.staff_id